controllers/PostController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Posts;
use app\models\PostLang;
use app\models\DashboardUsers;
use yii\web\Controller;
use yii\data\Pagination;

/**
 * PostController implements the CRUD actions for Posts model.
 */
class PostController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public $enableCsrfValidation = false;

    //get all posts for admin page
    public function actionGetAllPosts()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $language = Yii::$app->request->get('language') ? Yii::$app->request->get('language') : 'ua';
        $posts = Posts::find()
            ->select('*')
            ->leftJoin('postLang', '`postLang`.`post_id` = `posts`.`id`')
            ->where(['type' => 'post'])
            ->andWhere(['language' => $language])
            ->asArray()
            ->all();

        return $this->format_posts($posts)['rows'];
    }

    //format posts for showing them on front-end
    public function format_posts($posts = array(), $images_only = false, $language = 'ua')
    {
        $formatted_posts = array();
        if ($images_only) {
            foreach ($posts as $post) {
                $post_id = $post['post_id'];
                if (Posts::get_post_images($post_id)) {
                    $post['images'] = Posts::get_post_images($post_id);
                } else {
                    $post['images'][0] = array('image_url' => '/uploads/news-placeholder.png');
                }
                $post['author_name'] = Posts::get_post_author($post['author_id']);
                $post['created_at'] = Posts::date_format(strtotime($post['created_at']), $language);
                $post['updated_at'] = Posts::date_format(strtotime($post['updated_at']), $language);
                $formatted_posts[] = $post;
            }
            $formatted_posts = array_reverse($formatted_posts, true);

            return $formatted_posts;
        } else {
            foreach ($posts as $post) {
                $post_id = $post['post_id'];
                if (Posts::get_post_images($post_id)) {
                    $post['images'] = Posts::get_post_images($post_id);
                } else {
                    $post['images'][0] = array('image_url' => '/uploads/news-placeholder.png');
                }
                $post['author_name'] = Posts::get_post_author($post['author_id']);
                $post['created_at'] = Posts::date_format(strtotime($post['created_at']), $language);
                $post['updated_at'] = Posts::date_format(strtotime($post['updated_at']), $language);
                $formatted_posts[] = $post;
            }
            $formatted_posts = array_reverse($formatted_posts, true);

            return array('rows' => $formatted_posts);
        }
    }

    //Get posts per page
    public function actionGetPosts()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        //$page_id  = Yii::$app->request->get('page_id');
        //$pagination = new Pagination(['totalCount' => Posts::find()->count()]);
        //$pagination->pageSize = 4;
        //$pagination->page = $page_id;
        $language = Yii::$app->request->get('language', 'ua');

        $posts = Posts::find()
            ->select('title, post_id, author_id, created_at, updated_at, title_ua, excerpt, content')
            ->leftJoin('postLang', '`postLang`.`post_id` = `posts`.`id`')
            ->where(['type' => 'post'])
            ->andWhere(['language' => $language])
            ->andWhere(['not', ['title' => null]])
            ->andWhere(['not', ['content' => null]])
            //->offset($pagination->offset)
            //->limit($pagination->limit)
            ->orderBy('created_at DESC')
            ->asArray()
            ->all();

        $formatted_posts = $this->format_posts($posts, true, $language);

        return array('rows' => $formatted_posts);
    }

    public function actionGetPost()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $post_id = Yii::$app->request->get('post_id');

        return Posts::findOne($post_id);
    }

    public function actionCreate()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $user = new DashboardUsers();
        $request = Yii::$app->request;
        $token = $request->post('token');

        if ($user->checkRole($request)) {
            $user_id = DashboardUsers::getUserId($token);
            $category_id = $request->post('category_id');
            if (!$category_id) {
                $category_id = 1;
            }
            $new_post = new Posts();
            $new_post->author_id = $user_id;
            $new_post->category_id = $category_id;
            $new_post->type = $request->post('type');
            $new_post->updated_at = date('Y-m-d H:i:s');
            $new_post->save();

            $content_params['content'] = $request->post('content');
            $content_params['excerpt'] = $request->post('excerpt');
            $content_params['title'] = $request->post('title');

            $for_empty_params['title_ua'] = $request->post('title');
            Posts::create_post_translation($new_post->id, 'ua', $content_params);
            Posts::create_post_translation($new_post->id, 'ru', $for_empty_params);
            Posts::create_post_translation($new_post->id, 'en', $for_empty_params);

            if ($new_post->id) {
                return array('status' => 'ok', 'message' => 'done', 'post_id' => $new_post->id);
            }
            Yii::$app->response->statusCode = 500;
            $errors = array($new_post->errors);

            return array('status' => 'error', 'message' => array($errors));
        }
        Yii::$app->response->statusCode = 403;

        return array('status' => 'error', 'message' => "you don't have permissions to create posts");
    }

    /**
     * Updates an existing Posts model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param int $id
     *
     * @return mixed
     */
    public function actionUpdate()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $user = new DashboardUsers();
        $request = Yii::$app->request;
        $post_id = $request->post('post_id');

        if ($user->checkRole($request) && Posts::findOne(['id' => $post_id])) {
            $updated_post = Posts::findOne($post_id);
            $updated_post->type = $request->post('type');

            $translation = PostLang::find()
                        ->where(['post_id' => $post_id])
                        ->andWhere(['language' => $request->post('language')])
                        ->one();

            $translation->excerpt = $request->post('excerpt');
            $translation->content = $request->post('content');
            $translation->title = $request->post('title');

            if ($request->post('category_id')) {
                $updated_post->category_id = $request->post('category_id');
            }

            if ($updated_post->save() && $translation->save()) {
                return array('status' => 'ok', 'message' => 'done');
            } else {
                Yii::$app->response->statusCode = 500;
                $errors = array($updated_post->errors, $translation->errors);

                return array('status' => 'error', 'message' => array($errors));
            }
        } else {
            Yii::$app->response->statusCode = 403;

            return array('status' => 'error', 'message' => "you don't have permissions to edit posts");
        }
    }

    /**
     * Deletes an existing Posts model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param int $id
     *
     * @return mixed
     */
    public function actionDelete()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $user = new DashboardUsers();
        $request = Yii::$app->request;
        $post_id = $request->post('post_id');
        $post = Posts::findOne(['id' => $post_id]);
        $language = (Yii::$app->request->get('language') ? Yii::$app->request->get('language') : 'ua');
        $post_translation = PostLang::find_translation($post_id, $language);

        if ($user->checkRole($request) && $post && $post_translation) {
            if ($language === 'ua') {
                $post_translation->delete();
                $post->delete();
                Posts::delete_post_images($post_id);

                return array('status' => 'ok', 'message' => 'done');
            } else {
                $post_translation->delete();

                return array('status' => 'ok', 'message' => 'done');
            }
        }
        Yii::$app->response->statusCode = 500;

        return array('status' => 'error',
                    'message' => "permissions error or $post->errors $post_translation->errors", );
    }

    protected function findModel($id)
    {
        if (($model = Posts::findOne($id)) !== null) {
            return $model;
        } else {
            return false;
        }
    }

    // template action for news
    public function actionNews()
    {
        $language = substr(Yii::$app->language, 0, 2);
        $page_id = Yii::$app->request->get('page_id');
        $pagination = new Pagination(['totalCount' => Posts::find()->count()]);
        $pagination->pageSize = 4;
        $pagination->page = $page_id;

        $posts = Posts::find()
            ->select('title, post_id, author_id, created_at, updated_at, title_ua, excerpt, content')
            ->leftJoin('postLang', '`postLang`.`post_id` = `posts`.`id`')
            ->where(['type' => 'post'])
            ->andWhere(['language' => $language])
            ->andWhere(['not', ['title' => null]])
            ->andWhere(['not', ['content' => null]])
            ->offset($pagination->offset)
            ->limit($pagination->limit)

views/templates/error.php
<?php 

use yii\helpers\Url;

?>
<div class=preloader></div>
    <div class="wrapper page404 animated fadeIn" id=wrapper__404>
        <div class="text_parallax d-none d-lg-block">
            <div class=top_left_word>404</div>
            <div class=bottom_right_word>404</div>
        </div>
        <div class="section_404 flex-column d-flex justify-content-center">
            <div class=container>
                <div class=row>
                    <div class="col-12 d-flex justify-content-center">
                        <div class=logo>
                            <a class=pageSwitcher href=javascript:void(0) data-url=/>
                            <svg width=100 height=100 x=0px y=0px viewBox="0 0 600 600">
                                <polygon points="112.2,505.8 134.3,505.8 123.9,524.2 116.3,524.2 116.3,527.2 122.2,527.2 111.5,546.2 111.5,549.7 139.3,549.7 139.3,545.9 116.3,545.9 126.9,527.2 134.3,527.2 134.3,524.2 128.7,524.2 139.3,505.6 139.3,502.1 112.2,502.1"></polygon>
                                <polygon points="152.7,502.1 148.6,502.1 148.6,549.7 173.5,549.7 173.5,545.9 152.7,545.9"></polygon>
                                <path d="M194.1,502.1L176,549.7h4.6l5.5-14.9h20.4l5.7,14.9h4.6l-18.1-47.6H194.1z M187.4,530.9l8.9-23.5l8.8,23.5 H187.4z"></path>
                                <polygon points="246.6,502.1 216.1,502.1 216.1,505.8 229.4,505.8 229.4,549.7 233.5,549.7 233.5,505.8 246.6,505.8"></polygon>
                                <path d="M264.2,502.1l-18.1,47.6h4.6l5.5-14.9h20.4l5.7,14.9h4.6l-18.1-47.6H264.2z M257.6,530.9l8.9-23.5l8.8,23.5 H257.6z"></path>
                                <polygon points="302.6,505.8 315.9,505.8 315.9,549.7 319.9,549.7 319.9,505.8 333.1,505.8 333.1,502.1 302.6,502.1"></polygon>
                                <path d="M357.9,527.5c6-1.4,10.4-5.4,10.4-12.3c0-8.1-6-13.1-14.6-13.1h-12.9v47.6h4.1v-21h6.2c6.4,0,13.4,8.4,15.8,21 h4.2C369.1,537.8,363.5,529.9,357.9,527.5z M345,524.9v-19h8.8c6,0,10.4,3.6,10.4,9.6c0,6.1-4.4,9.5-10.4,9.5L345,524.9z"></path>
                                <path d="M393.2,502.1l-18.1,47.6h4.6l5.5-14.9h20.4l5.7,14.9h4.6l-18.1-47.6H393.2z M386.5,530.9l8.9-23.5l8.8,23.5 H386.5z"></path>
                                <path d="M440,502.1h-16.3v47.6H440c14.1,0,23.2-9.9,23.2-23.8S454.1,502.1,440,502.1z M439.9,545.9h-12.2v-40h12.2 c11.7,0,19,8.5,19,20C459,537.4,451.6,545.9,439.9,545.9z"></path>
                                <polygon points="473.2,549.7 498.1,549.7 498.1,545.9 477.3,545.9 477.3,527.6 496.7,527.6 496.7,523.8 477.3,523.8 477.3,505.8 498.1,505.8 498.1,502.1 473.2,502.1 	"></polygon>
                                <path d="M410.5,76.5l20-0.9c0.9,0,1.5,1,1,1.8L423.4,90c-0.2,2.6,1.8,4.8,4.4,5c6.8,0.5,30.9,5.8,57,53.8 c0.7,1.3,2.1,2.1,3.5,2.1c0.4,0,0.7,0,1.1-0.2c1.7-0.5,2.9-2.1,2.9-3.9c0.1-1.6,0.2-3.7,0.3-6.1c1-17,2.9-48.1-5-68l4.8-1.6 c1.3-0.4,2.1-1.6,2.2-2.9c0-1.1-0.6-2.1-1.5-2.7c-6.6-4.5-20.2-9.4-20.8-9.6c-30.2-10.7-55.5-2.3-61.8,4.4 c-4.2,4.5-4.5,9.3-4.4,11.8C406.2,74.6,408.1,76.4,410.5,76.5z M414.3,64.1c4.8-5,27.7-13.1,56-3c0.1,0,8.9,3.2,15.4,6.6l-2.1,0.7 c-0.9,0.3-1.6,1-2,1.8c-0.4,0.9-0.4,1.9,0,2.7c8.4,18.4,6.4,51.6,5.5,67.5c0,0.5-0.1,0.9-0.1,1.4c-11-19.2-22.9-33.5-35.3-42.5 c-10.3-7.4-18.5-9.3-22.9-9.8l9.4-14.5c1.2-1.8-0.1-4.3-2.3-4.2L411.3,71C411.4,69.2,412,66.6,414.3,64.1z"></path>
                                <path d="M390.2,130.3l0.8-5.9c0-0.1,1.5-9.9,9.2-15.1c5.3-3.6,12.3-4.3,21-2.2c1.7,0.4,3.5-0.6,4.2-2.3 c0.6-1.6-0.1-3.3-1.6-4c-4.2-2.1-6.9-7.5-6.2-12.3c0.3-2-0.3-3.9-1.6-5.4c-1.3-1.5-3.3-2.4-5.3-2.4h-12.9c-2.1,0-4.2,0.7-5.9,2.1 c-4.7,3.7-12.6,11.6-13.5,22.2c-0.6,7.1,2,14.1,7.9,20.8L390.2,130.3z M383.8,105.5c0.8-9,8.3-15.9,11.5-18.5 c0.7-0.6,1.6-0.9,2.5-0.9h12.9c0.5,0,0.9,0.2,1.2,0.5c0.2,0.2,0.4,0.6,0.3,1.1c-0.6,4.5,0.7,9.2,3.4,12.9 c-7.2-0.7-13.4,0.7-18.5,4.2c-5.5,3.7-8.4,9.1-10,13.2C384.6,113.9,383.5,109.7,383.8,105.5z"></path>
                                <path d="M266.8,346.9l-2.7,7.9c-0.8,2.3,0.1,4.9,2.3,6.2l2.5,1.5l10.3,43.5h-44.5c-1.5,0-2.7,1.2-2.7,2.7 s1.2,2.7,2.7,2.7h46.9c0.8,0,1.6-0.2,2.2-0.7c1-0.8,1.4-2.1,1.2-3.4l-10.9-46c-0.3-1.4-1.2-2.6-2.4-3.3l-2.4-1.5l9.3-27.1l30.2-7.1 L286,358.7h-1.8c-1.2,0-2.3,0.4-3.2,1.2c-1.3,1.2-1.8,2.9-1.4,4.5l10.9,44.4c0.4,1.5,1.7,2.5,3.2,2.5h24.5c0.9,0,1.7-0.3,2.4-0.9 c1.1-1,1.4-2.5,0.8-3.7l-15.8-38.3c-0.7-1.5-1.6-2.9-2.8-4.1l-2.8-2.7l31.3-44.6l30.5-7.2c0.4-0.1,0.9,0.1,1.1,0.5 c0.7,1.3,1.7,3.7,0.8,5.4c-1.6,2.9-25.4,28.8-48.2,53.3c-1.5,1.7-2,4.1-1.2,6.1l12.6,34c0.5,1.3,1.7,2.2,3.1,2.2h90.1 c1.5,0,2.7-1.2,2.7-2.7s-1.2-2.7-2.7-2.7h-88.7l-12.1-32.7c-0.1-0.2,0-0.4,0.1-0.6c14-15,46.8-50.3,49-54.4 c1.5-2.9,1.3-6.5-0.8-10.4c-1.4-2.6-4.3-3.9-7.1-3.3l-40.4,9.5l-45.8,10.7L209.6,340l29.6-14.1c1.5-0.7,2.5-2.2,2.6-3.9l1.6-33.6 c0.1-1.3-0.6-2.4-1.7-3c-1.1-0.6-2.5-0.5-3.5,0.2l-82.8,59.9c-2,1.4-3,3.8-2.7,6.2c0.3,2.4,0.2,6.9-3,11l-15.2,7.3 c-1.3,0.6-1.9,2.2-1.3,3.6c0.6,1.3,2.2,1.9,3.6,1.3l39.3-18.7l-40,69.7c-0.7,1.3-0.7,2.8,0,4s2.1,2,3.5,2h34.3c1,0,2-0.4,2.8-1.1 L266.8,346.9z M323.4,318.8L295.2,359c-1.4,1.9-1.1,4.5,0.6,6.2l3.2,3.1c0.7,0.6,1.2,1.4,1.6,2.3l14.6,35.5h-20L285,364h1.3 c1.6,0,3-0.8,3.9-2.1l25.9-41.4L323.4,318.8z M157.5,358.9c0.8-3.1,0.7-5.9,0.5-7.8c-0.1-0.5,0.2-1,0.6-1.3l79.3-57.4l-1.4,28.8 L157.5,358.9z M173,425.8h-30.1l42.6-74.3l1.5-0.7l85.3-20l-1.4,4.1L173,425.8z"></path>
                                <path d="M314.3,232.6c-1.3-0.6-2.8-0.5-4,0.3l-60,43.4c-1.5,1.1-2.4,2.8-2.5,4.6l-1.7,35.8c-0.1,1.3,0.6,2.6,1.7,3.3 c0.6,0.4,1.3,0.6,2.1,0.6c0.5,0,1.1-0.1,1.6-0.4l62.9-30c1.8-0.9,3-2.7,2.9-4.7l-1-49.6C316.4,234.5,315.6,233.3,314.3,232.6z M252.3,313.3l1.5-32.1l56.7-41l0.9,44.9L252.3,313.3z"></path>
                                <path d="M210.6,275l30.6,1.8c0.1,0,0.2,0,0.3,0c1.1,0,2.2-0.4,3.1-1l57.7-42.5c1.3-1,1.9-2.7,1.3-4.2 c-0.5-1.5-1.9-2.6-3.6-2.6h-46.7c-1.7,0-3.3,0.7-4.5,1.8L208,268.4c-1.1,1.1-1.5,2.7-0.9,4.1C207.7,273.9,209.1,274.9,210.6,275z M253,232.6c0.1-0.1,0.2-0.1,0.3-0.1h39.9l-52,38.3l-25.5-1.5L253,232.6z"></path>
                                <path d="M262.9,223l53.2-1.7c1.7-0.1,3.3-0.6,4.7-1.6l66.3-48.8c2.4-1.4,39.5-22.8,61.7-20.9 c24.6,2.1,47.6,15.8,49.3,29.2c2,15.7-5.8,61.8-16.8,77.9c-7.5,11-36.5,26.6-59,36.6c-0.8,0.4-1.6,0.6-2.5,0.7l-11.4,1.7 c26.3-11.5,61.9-28.7,68.9-40.5c5.1-8.6,10.3-23.9,13.7-40c1.7-8.2,5.4-28.3,1.8-38.1c-3.5-9.4-12.6-15.1-19.7-18.3 c-8.4-3.7-18.5-5.8-27.2-5.7c-16.3,0.3-55.1,21.5-56.7,22.4L389,176l-62.4,45.1c-1.4,1-2.3,2.6-2.3,4.4l-2.3,54.9 c-0.1,1.4,0.6,2.7,1.8,3.4s2.7,0.8,3.9,0.2c9.7-5,41.7-21.7,48.3-29.1c7.7-8.6,25.7-58.8,25.7-63.5c0-3.6-3.5-8.6-6.3-11.9 c9.7-5.1,38.3-19.6,50.6-19.9c21.9-0.4,38,11.4,41.1,20c4.1,11.1-3.7,53.7-15.1,73c-6.5,11.1-49.8,31.7-84.8,46 c-1.6,0.6-2.5,2.4-2,4c0.4,1.5,1.8,2.5,3.3,2.5c0.2,0,0.3,0,0.5,0l31.6-4.6c1.4-0.2,2.8-0.6,4.1-1.2c11.8-5.2,51.2-23.5,61.5-38.7 c11.8-17.3,19.9-65.2,17.7-82c-2.4-18.5-30.3-32.3-54.8-34.4c-21.2-1.8-52.9,14.8-62.6,20.2c-0.7-3.9,1-11.1,4.7-19.5 c0.7-1.6,0.1-3.4-1.4-4.3s-3.4-0.5-4.4,0.9c-3.7,5-11.1,13.5-19.4,15c-57.1,10.1-76.6,31.7-78.4,33.9L260.3,217 c-1,1-1.3,2.5-0.8,3.9C260.1,222.2,261.4,223.1,262.9,223z M395.7,191.2c-0.4,4.9-17.9,52.5-24.2,59.6c-4.4,5-25.4,16.8-43.3,26.1 l2.2-51.1l59.9-43.3C393.3,186.1,395.7,189.9,395.7,191.2z M292,194.3l0.2-0.3c0.2-0.2,18.2-21.9,74.9-31.9 c5.4-1,10.3-4.1,14.4-7.7c-1.3,5.5-1.4,9.9-0.1,13.1l-64.2,47.3c-0.4,0.3-0.8,0.4-1.3,0.4l-46.8,1.5L292,194.3z"></path>
                                <path d="M115.2,367.6l23.7-23.3c2.5-0.2,4.5,0,5.9,0.3c2.8,0.6,5.8-0.1,8.2-1.9l78.4-57.7c1.1-0.8,1.6-2.2,1.2-3.5 c-0.4-1.3-1.5-2.3-2.9-2.4l-27.2-2.1c-1.7-0.1-3.3,0.5-4.5,1.6l-86.5,85.1c-1.1,1-1.1,2.7,0,3.8 C112.5,368.6,114.2,368.7,115.2,367.6z M201.7,282.6c0.1-0.1,0.2-0.1,0.3-0.1l21.6,1.6l-73.9,54.4c-1.2,0.9-2.6,1.2-4,0.9 c-0.5-0.1-1.1-0.2-1.6-0.3L201.7,282.6z"></path>
                                <path d="M437.6,420.7c0-1.5-1.2-2.7-2.7-2.7H248.2c-1.5,0-2.7,1.2-2.7,2.7s1.2,2.7,2.7,2.7H435 C436.4,423.4,437.6,422.2,437.6,420.7z"></path>
                                <rect x=202 y=495.5 transform="matrix(0.7072 -0.707 0.707 0.7072 -291.2963 290.5467)"
                                    width=6.3 height=3></rect>
                                <rect x=400.3 y=495.6 transform="matrix(0.7072 -0.707 0.707 0.7072 -233.3349 430.7701)"
                                    width=6.3 height=3></rect>
                            </svg>
                            </a>
                        </div>
                    </div>
                </div>
                <div class=row>
                    <div class=col-12>
                        <h1 class=text-center style="font-size: 2.5em;color: white;margin-bottom: .7em;"><?=$pageNotFoundText; ?></h1>
                    </div>
                </div>
                <div class=row>
                    <div class=col-12>
                        <h2 class=text-center style="font-size: 1.5em;color: white;margin-bottom: .5em;"><?=$VisitOurOtherPagesText; ?></h2>
                    </div>
                </div>
                <div class=row>
                    <div class="col-12 col-md-4 mb-2 d-flex justify-content-center">
                        <button class="btn btn_white pageSwitcher" data-url=<?=Url::to(['/', 'language' => Yii::$app->language]); ?>>
                        <span><?=$mainText; ?></span>
                        </button>
                    </div>
                    <div class="col-12 col-md-4 mb-2 d-flex justify-content-center">
                        <button class="btn btn_white pageSwitcher" data-url=<?=Url::to(['services/services', 'language' => Yii::$app->language]); ?>>
                            <span><?=$activityText; ?></span>
                        </button>
                    </div>
                    <div class="col-12 col-md-4 mb-2 d-flex justify-content-center">
                        <button class="btn btn_white pageSwitcher" data-url=<?=Url::to(['post/news', 'language' => Yii::$app->language]); ?>>
                            <span><?=$publication; ?></span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>